"""users table

Revision ID: ddaac397d217
Revises: 
Create Date: 2020-01-26 14:35:02.083271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddaac397d217'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('daystobirthday', sa.String(length=5), nullable=True))
    op.drop_column('person', 'username')
    op.drop_column('person', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('datetime', sa.DATETIME(), nullable=True))
    op.add_column('person', sa.Column('username', sa.VARCHAR(length=80), nullable=True))
    op.drop_column('person', 'daystobirthday')
    # ### end Alembic commands ###
